// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Flashcard struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Title           string
	Body            string
	Tags            []string
	LastReviewedAt  sql.NullTime
	ReviewCount     sql.NullInt32
	CorrectCount    sql.NullInt32
	DifficultyLevel sql.NullInt32
	UserID          uuid.UUID
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	FirstName    string
	LastName     string
	Email        string
	Password     string
	ProfileImage []byte
}
